// flow-typed signature: a6503d4d5ac4c119dcc1f5289c4bc8c3
// flow-typed version: <<STUB>>/@kadira/storyshots_v^1.1.3/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/storyshots'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/storyshots' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/storyshots/bin/run_storyshots' {
  declare module.exports: any;
}

declare module '@kadira/storyshots/dist/cli' {
  declare module.exports: any;
}

declare module '@kadira/storyshots/dist/default_config/loaders' {
  declare module.exports: any;
}

declare module '@kadira/storyshots/dist/default_config/polyfills' {
  declare module.exports: any;
}

declare module '@kadira/storyshots/dist/require_context' {
  declare module.exports: any;
}

declare module '@kadira/storyshots/dist/test_runner/index' {
  declare module.exports: any;
}

declare module '@kadira/storyshots/dist/test_runner/snapshot_runner' {
  declare module.exports: any;
}

declare module '@kadira/storyshots/dist/util' {
  declare module.exports: any;
}

declare module '@kadira/storyshots/examples/button' {
  declare module.exports: any;
}

declare module '@kadira/storyshots/examples/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/storyshots/bin/run_storyshots.js' {
  declare module.exports: $Exports<'@kadira/storyshots/bin/run_storyshots'>;
}
declare module '@kadira/storyshots/dist/cli.js' {
  declare module.exports: $Exports<'@kadira/storyshots/dist/cli'>;
}
declare module '@kadira/storyshots/dist/default_config/loaders.js' {
  declare module.exports: $Exports<'@kadira/storyshots/dist/default_config/loaders'>;
}
declare module '@kadira/storyshots/dist/default_config/polyfills.js' {
  declare module.exports: $Exports<'@kadira/storyshots/dist/default_config/polyfills'>;
}
declare module '@kadira/storyshots/dist/require_context.js' {
  declare module.exports: $Exports<'@kadira/storyshots/dist/require_context'>;
}
declare module '@kadira/storyshots/dist/test_runner/index.js' {
  declare module.exports: $Exports<'@kadira/storyshots/dist/test_runner/index'>;
}
declare module '@kadira/storyshots/dist/test_runner/snapshot_runner.js' {
  declare module.exports: $Exports<'@kadira/storyshots/dist/test_runner/snapshot_runner'>;
}
declare module '@kadira/storyshots/dist/util.js' {
  declare module.exports: $Exports<'@kadira/storyshots/dist/util'>;
}
declare module '@kadira/storyshots/examples/button.js' {
  declare module.exports: $Exports<'@kadira/storyshots/examples/button'>;
}
declare module '@kadira/storyshots/examples/index.js' {
  declare module.exports: $Exports<'@kadira/storyshots/examples/index'>;
}
declare module '@kadira/storyshots/index' {
  declare module.exports: $Exports<'@kadira/storyshots'>;
}
declare module '@kadira/storyshots/index.js' {
  declare module.exports: $Exports<'@kadira/storyshots'>;
}
